# Configuration to setup auto building in Read the Docs.
#
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-24.04"
  # Opting to use system packages instead of Python packages.
  apt:
    - mkdocs
    - mkdocs-material
  tools:
    python: "3"

mkdocs:
  configuration: mkdocs.yml
