#
# Makefile --Build rules for makeshift, a make-based build system.
#
# Contents:
# makeshift.mk:        --Fail if makeshift is not available.
# makeshift-version.mk: --Install a file recording the makeshift version.
# distclean:           --Remove makeshift-version.mk.
#
# SPDX-FileCopyrightText: 2006-2023 Tim Rose <tim.rose@acm.org>
# SPDX-License-Identifier: MIT
#
language = markdown
PACKAGE = makeshift
package-type = rpm deb

DEB_ARCH = all
RPM_ARCH = noarch

MD_SRC = README.md RELEASE.md
MK_SRC = makeshift-version.mk
VERSION_CMD = git describe --always --first-parent --dirty 2>/dev/null || echo unknown
export VERSION = $(shell $(VERSION_CMD))

include makeshift.mk make/package.mk

$(DESTDIR_ROOT):
	$(ECHO_TARGET)
	$(MAKE) install DESTDIR=$$(pwd)/$@ prefix=$(prefix) usr=$(usr) opt=$(opt)

SPECS/makeshift.spec: Makefile

#
# makeshift.mk: --Fail if makeshift is not available.
#
$(includedir)/makeshift.mk:
	@echo "You need to do a self-hosted install:"
	@echo "    sh install.sh [make-arg.s...]"
	@false

#
# makeshift-version.mk: --Install a file recording the makeshift version.
#
install:	$(includedir)/makeshift-version.mk

$(includedir)/makeshift-version.mk: makeshift-version.mk
	$(ECHO_TARGET)
	$(INSTALL_DATA) $? $@

makeshift-version.mk:
	$(ECHO_TARGET)
	date "+# DO NOT EDIT.  This file was generated by $$USER. %c" >$@
	echo "export MAKESHIFT_VERSION=$$($(VERSION_CMD))" >>$@

uninstall:	uninstall-local
uninstall-local:
	$(ECHO_TARGET)
	$(RM) $(includedir)/makeshift-version.mk
	-$(RMDIR) -p $(includedir) 2>/dev/null

#
# distclean: --Remove makeshift-version.mk.
#
clean:	clean-local
distclean:	clean-local
clean-local:
	$(RM) makeshift-version.mk
