#
# Makefile --Build rules the devkit's skel directory. 
#
# Remarks:
# The skel directory contains "skeleton" template files
# that can be used as a common starting point.
#
MAKEFLAGS = -I ../make

include devkit.mk
