#
# Makefile --Build rules for the package directory of devkit.
#
MK_SRC = aip.mk deb.mk recursive.mk rpm.mk rpm-repo.mk
subdir	= package

include devkit.mk

install: install-mk
uninstall: uninstall-mk
