#
# .MK --Fallback make definitions for OS customisation.
#
# Remarks:
# Do not edit this file! 
# it was automatically generated on Fri May 25 10:05:15 EST 2012
#
$(info "OS" must have one of the following values:)
$(info darwin linux solaris windows_nt)
$(error The variable "OS" is not defined. )
