#
# Makefile --Build rules for the os directory of devkit.
#
MK_SRC = cygwin_nt.mk darwin.mk linux.mk rtx.mk solaris.mk \
    unknown.mk windows_nt.mk windriver-x.mk
subdir	= os

include devkit.mk

install:	install-mk
