#
# Makefile --Build rules for the os directory of makeshift.
#
MK_SRC = cygwin_nt.mk darwin.mk freebsd.mk linux.mk mingw64_nt.mk \
    posix.mk rtx.mk solaris.mk unknown.mk Windows_NT.mk
subdir	= os

include makeshift.mk

install:	install-mk
uninstall:	uninstall-mk
