title: Recursive Make Considered Useful
css: doc.css
css: highlight/styles/default.css
html header: <script src="highlight/highlight.pack.js"></script>
html header: <script>hljs.initHighlightingOnLoad();</script>

# [%title]

## Introduction

This document is written as a review of and response to Peter Miller's
insightful critique of make, and the problems that arise with using it
to build large projects.

## Background

## But Nowadays...

It's all about chunking, co-locating make rules with the files they
build from, composibility.

## Recursive Make Done Properly

### Make Jobs

## Arranging Files in a Project

## Macro Evaluation
