#
# Makefile --Build rules for devkit/lib.
#
# Remarks:
# This directory contains shell library code; at the moment
# an implementation of the tap protocol.
#
language = sh
SHL_SRC = tap.shl test-more.shl

include devkit.mk

install:	install-shell
uninstall:	uninstall-shell
