#!/bin/sh
#
# _MK.SH	--Create the fallback ".mk" file for the OS directory
#
date=$(date)
cat <<EOF
#
# PROJECT-.MK	--Default customisations for a project.
#
# Remarks:
# The project include file defines overall customisations for existing
# rules. This is the "no-project" project, which contains some default
# settings to consider as a template.
#
# Do not edit this file!
# It was automatically generated on $date
#
PROJECT.C_DEFS =
PROJECT.C++_DEFS =

PROJECT.CFLAGS = -std=c99 -O
PROJECT.C_WARN_FLAGS = -pedantic -Wall -Wextra -Wmissing-prototypes \\
	-Wmissing-declarations 	-Wimplicit -Wpointer-arith \\
	-Wwrite-strings -Waggregate-return -Wnested-externs \\
	-Wcast-align -Wshadow -Wstrict-prototypes -Wredundant-decls \\
        -Wno-gnu-zero-variadic-macro-arguments

PROJECT.CXXFLAGS = -std=c++0x -O
PROJECT.C++_WARN_FLAGS = -pedantic -Wall -Wextra \\
        -Wpointer-arith -Wwrite-strings \\
        -Wcast-align -Wshadow -Wredundant-decls \\
	-Wno-variadic-macros
EOF
