#
# Makefile --Build rules for the project directory of makeshift.
#
# Remarks:
# This just installs a default project file, it's up to
# particular projects to copy in their own project-specific stuff.
#
MK_SRC = default.mk
subdir = project

include makeshift.mk

install:	install-mk
uninstall:	uninstall-mk
