#
# .MK --Fallback make definitions for VCS customisation.
#
# Remarks:
# Do not edit this file! 
# it was automatically generated on Fri May 25 10:05:15 EST 2012
#
$(info "VCS" must have one of the following values:)
$(info git svn)
$(error The variable "VCS" is not defined. )
