#
# .MK --Fallback make definitions for ARCH customisation.
#
# Remarks:
# Do not edit this file! 
# it was automatically generated on Fri May 25 10:05:15 EST 2012
#
$(info "ARCH" must have one of the following values:)
$(info all arm avr i386 i386_64 i686 i686_64 x86_64)
$(error The variable "ARCH" is not defined. )
