#
# Makefile --Build rules for the test directory of makeshift.
#
# Remarks:
# This directory contains some helper rules for various
# test frameworks.
#
MK_SRC = google.mk nunit.mk phpunit.mk pytest.mk tap.mk
subdir	= test

include makeshift.mk

install:	install-mk
uninstall:	uninstall-mk
