#
# PHPUNIT.MK --Rules for running tests with PHP's phpunit framework.
#
# Contents:
# test:            --Run all tests, and save the results to phpunit.xml.
# test-phpunit[%]: --Run an individual test.
# clean-phpunit:   --Cleanup files generated by running tests.
#
# Remarks:
# These rules runs the tests in the current directory according to
# phpunit's odd ideas for finding tests (you can't name the tests
# explicitly, you name the directory containing them, and phpunit
# "discovers" them according to some pattern).
#

PHP_TESTS ?= $(PHP_SRC)
PHPUNIT ?= phpunit
ALL_PHPUNIT_FLAGS = $(TARGET.PHPUNIT_FLAGS) $(LOCAL.PHPUNIT_FLAGS) \
    $(PROJECT.PHPUNIT_FLAGS) $(ARCH.PHPUNIT_FLAGS) $(OS.PHPUNIT_FLAGS) \
    $(PHPUNIT_FLAGS)

#
# test: --Run all tests, and save the results to phpunit.xml.
#
test:	test-phpunit

test-phpunit:
	$(PHPUNIT) $(ALL_PHPUNIT_FLAGS) --log-junit phpunit-tests.xml .

#
# test-phpunit[%]: --Run an individual test.
#
test[%]:
	$(PHPUNIT) $(ALL_PHPUNIT_FLAGS) --log-junit $*.xml $*.php

clean:		clean-phpunit
distclean:	clean-phpunit

#
# clean-phpunit: --Cleanup files generated by running tests.
#
.PHONY:		clean-phpunit
clean-phpunit:
	$(RM) -r $(PHP_TESTS:%.php=%.xml) phpunit-tests.xml
