#
# PHPUNIT.MK --Rules for running tests with PHP's phpunit framework.
#
# Contents:
# test:           --Run all tests, and save the results to pytest.xml.
# test-phpunit[%]: --Run an individual test.
# clean-phpunit:   --Cleanup files generated by running tests.
#
# Remarks:
# These rules runs the tests defined by the PHP_TESTS explicitly.
#

PHP_TESTS ?= $(PHP_SRC)
PHPUNIT ?= phpunit

#
# test: --Run all tests, and save the results to phpunit.xml.
#
test:	test-phpunit

test-phpunit:
	$(PHPUNIT) --log-junit php-tests.xml $(PHP_TESTS)

#
# test-phpunit[%]: --Run an individual test.
#
test[%.php]:
	$(PHPUNIT) $*.php


clean:		clean-phpunit
distclean:	clean-phpunit

#
# clean-phpunit: --Cleanup files generated by running tests.
#
.PHONY:		clean-phpunit
clean-phpunit:
	$(RM) -r $(PHP_TESTS:%.php=%.xml) php-tests.xml
