#
# PYTEST.MK --Rules for running tests with Python's "pytest" framework.
#
# Contents:
# test:           --Run all tests, and save the results to pytest.xml.
# test-pytest[%]: --Run an individual test.
# clean-pytest:   --Cleanup files generated by running tests.
#
# Remarks:
# These rules runs the tests defined by the PY_TESTS explicitly.
#

PY_TESTS ?= $(PY_SRC)
PYTEST ?= py.test

#
# test: --Run all tests, and save the results to pytest.xml.
#
test:	test-pytest

test-pytest:
	$(PYTEST) --junit-xml pytest.xml $(PY_TESTS)

#
# test-pytest[%]: --Run an individual test.
#
test[%.py]:
	$(PYTEST) $*.py


clean:		clean-pytest
distclean:	clean-pytest

#
# clean-pytest: --Cleanup files generated by running tests.
#
.PHONY:		clean-pytest
clean-pytest:
	$(RM) -r __pycache__ $(PY_TESTS:%.py=%.xml) pytest.xml
