#
# devkit.mk --Recursive make considered useful.
#
# Contents:
# build:     --The default target
# STD_DIR:   --The standard target directories are built as needed.
# INSTALL_*: --Specialised install commands.
# install:   --common requirements of the install target(s)
# src:       --Make sure the src target can write to the Makefile
# clean:     --Devkit-specific customisations for the "clean" target.
# distclean: --devkit-specific customisations for the "distclean" target.
#
# Remarks:
# These makefiles taken together define a build system that extends
# the "standard" targets (as documented by GNU make) with a few extras
# for performing common maintenance functions.  The basic principles
# are:
#
# * the standard make targets are magically recursive
# * $(LANGUAGE).mk extends standard targets by defining "dependent" actions
# * per-system tool customisations defined in $(OS).mk, $(ARCH).mk
# * all system-specific files are saved in $(archdir) subdirectory
# * file dependencies are auto-included, and auto-generated by build target.
# * traditional macros work as expected (e.g. CFLAGS, LDFLAGS)
# 
# This file defines variables according to the conventions described
# in the GNU make documentation (c.f. "Makefile Conventions" section).
#
# Note that I'm not being truly faithful to the GNU doc.s, in particular
# I avoid the $(archdir) suffix, for most of the installation directories.
# I'm sure this will come back to bite me later...
#
SUBDIRS := $(shell find . -maxdepth 1 -type d -name '[^.]*' | cut -d/ -f2)
ECHO = :				# enable by: make ECHO=echo
SHELL	= /bin/sh
archdir	= $(OS)-$(ARCH)

.SUFFIXES:			# remove default suffix rules

#
# build: --The default target
#
build:	; 	@$(ECHO) "++ make[$@]@$$PWD"
all:	build
#
# Standard directories
#
#exec_prefix = $(DESTDIR)/$(prefix)/$(archdir)	# (GNU std)
prefix_opt 	= $(prefix)/$(opt)
exec_prefix	= $(DESTDIR)/$(prefix_opt)

bindir		= $(exec_prefix)/bin
sbindir 	= $(exec_prefix)/sbin
#libexecdir	= $(exec_prefix)/libexec/$(archdir)
libexecdir	= $(exec_prefix)/libexec/$(subdir)

sysconfdir	= $(DESTDIR)/etc/$(opt)/$(subdir)
divertdir	= $(DESTDIR)/var/lib/divert/$(subdir)
sharedstatedir	= $(DESTDIR)/$(prefix_opt)/com/$(subdir)
localstatedir	= $(DESTDIR)/var/$(opt)/$(subdir)
datadir		= $(DESTDIR)/$(prefix_opt)/share/$(subdir)
srvdir 		= $(DESTDIR)/$(prefix)/srv/$(subdir)
wwwdir 		= $(DESTDIR)/$(prefix)/srv/www/$(subdir)

#libdir		= $(exec_prefix)/lib/$(archdir)	# (GNU std)
libdir		= $(exec_prefix)/lib/$(subdir)
perllibdir	= $(exec_prefix)/lib/perl5/$(subdir)
infodir		= $(DESTDIR)/$(prefix_opt)/info
lispdir		= $(DESTDIR)/$(prefix_opt)/share/emacs/site-lisp

includedir	= $(DESTDIR)/$(prefix_opt)/include/$(subdir)
mandir		= $(datadir)/man
man1dir		= $(mandir)/man1
man3dir		= $(mandir)/man3
man4dir		= $(mandir)/man4

#
# STD_DIR: --The standard target directories are built as needed.
#
# Remarks:
# Note that we avoid using "mkdir -p", but use "install -d" instead,
# mainly because the GNU Make doc.s deprecate "mkdir -p".
#
# This target obviates the need for installdirs (mostly), provided
# the install targets themselves declare a dependency on the directory.
#
$(archdir) $(bindir) $(sbindir) $(libexecdir) \
    $(sysconfdir) $(divertdir) \
    $(sharedstatedir) $(localstatedir) \
    $(datadir) $(srvdir) $(wwwdir) \
    $(libdir) $(perllibdir) $(infodir) $(lispdir) \
    $(includedir) $(mandir) $(man1dir) $(man3dir) $(man4dir):
	test -d '$@' || $(INSTALL_DIRECTORY) $@

#
# INSTALL_*: --Specialised install commands.
#
# Remarks:
# Script installation is a little messy because I'm re-writing the
# first-line '#!' magic to the target host's script-path.
# REVISIT: consider using "#!/env", instead of this silliness.
#
INSTALL 	  = install
INSTALL_PROGRAM   = $(INSTALL) -m 755
INSTALL_DATA      = $(INSTALL) -m 644
INSTALL_DIRECTORY = $(INSTALL) -d
INSTALL_SCRIPT = install_script() { \
    echo "$(INSTALL_PROGRAM) $$2 $$3"; \
    <$$2 sed -e "1s|!.*|!$$1|" > $$$$.tmp \
    && $(INSTALL_PROGRAM) $$$$.tmp $$3 \
    && $(RM) $$$$.tmp; }; install_script

#
# src: --Make sure the src target can write to the Makefile
#
src:			file-writable[Makefile]

#
# bindir/archdir: --rules for installing any executable in archdir.
#
$(bindir)/%:		$(archdir)/%;	$(INSTALL_PROGRAM) $? $@
$(libexecdir)/%:	$(archdir)/%;	$(INSTALL_PROGRAM) $? $@

#
# %.gz: --Rules for building compressed/summarised data.
#
%.gz:			%;		gzip -9 <$* >$@
%.gpg:			%;		gpg -b -o $* $@
%.sum:			%;		sum $* | sed -e 's/ .*//' >$@

#
# clean: --Devkit-specific customisations for the "clean" target.
#
clean:	devkit-clean
.PHONY:	devkit-clean
devkit-clean:
	@$(ECHO) "++ make[$@]@$$PWD"
	$(RM) core *~ *.bak *.tmp *.out

#
# distclean: --devkit-specific customisations for the "distclean" target.
#
distclean:	devkit-clean devkit-distclean
.PHONY:	devkit-distclean
devkit-distclean:
	@$(ECHO) "++ make[$@]@$$PWD"
	$(RM) tags TAGS
	$(RM) -r $(OS) $(ARCH) $(archdir)

include targets.mk valid.mk
include lang/mk.mk $(LANG:%=lang/%.mk)
include os/$(OS).mk
include arch/$(ARCH).mk
include vcs/$(VCS).mk

#
# print-%:	pattern rule to print a make variable.
#
print-%:
	@echo "# in $(origin $*):"
	@echo "# $* = $(value $*)"
	@echo "$* = $($*)"
