#
# Makefile --Build rules for the lang directory of devkit.
#
MK_SRC = asciidoc.mk c.mk c++.mk c++-library.mk c-library.mk conf.mk \
    cron.mk cs.mk css.mk elisp.mk img.mk java.mk javascript.mk \
    lex.mk lex-library.mk markdown.mk mk.mk nroff.mk perl.mk \
    php.mk protobuf.mk protobuf-library.mk python.mk qt.mk \
    qt-library.mk ruby.mk sh.mk sql.mk tex.mk vsproj.mk xml.mk \
    xsd.mk xsd-library.mk xsl.mk yacc.mk yacc-library.mk
subdir	= lang

include devkit.mk

install:		install-mk
uninstall:		uninstall-mk

